wos_category_names = {
    # 'FN': 'File Name',
    # 'VR': 'Version Number',
    # 'PT': 'Publication Type (J=Journal; B=Book; S=Series; P=Patent)',
    # 'AU': 'Authors',
    # 'AF': 'Author Full Name',
    # 'BA': 'Book Authors',
    # 'BF': 'Book Authors Full Name',
    # 'CA': 'Group Authors',
    # 'GP': 'Book Group Authors',
    # 'BE': 'Editors',
    'TI': 'title',
    # 'SO': 'Publication Name',
    # 'SE': 'Book Series Title',
    # 'BS': 'Book Series Subtitle',
    # 'LA': 'Language',
    # 'DT': 'Document Type',
    # 'CT': 'Conference Title',
    # 'CY': 'Conference Date',
    # 'CL': 'Conference Location',
    # 'SP': 'Conference Sponsors',
    # 'HO': 'Conference Host',
    # 'DE': 'Author Keywords',
    # 'ID': 'Keywords Plus®',
    'AB': 'abstract',
    # 'C1': 'Author Address',
    # 'RP': 'Reprint Address',
    # 'EM': 'E-mail Address',
    # 'RI': 'ResearcherID Number',
    # 'OI': 'ORCID Identifier (Open Researcher and Contributor ID)',
    # 'FU': 'Funding Agency and Grant Number',
    # 'FX': 'Funding Text',
    # 'CR': 'Cited References',
    # 'NR': 'Cited Reference Count',
    # 'TC': 'Web of Science Core Collection Times Cited Count',
    # 'Z9': 'Total Times Cited Count',
    # 'U1': 'Usage Count (Last 180 Days)',
    # 'U2': 'Usage Count (Since 2013)',
    # 'PU': 'Publisher',
    # 'PI': 'Publisher City',
    # 'PA': 'Publisher Address',
    'SN': 'ISSN',
    'EI': 'eISSN',
    'BN': 'ISBN',
    # 'J9': '29-Character Source Abbreviation',
    # 'JI': 'ISO Source Abbreviation',
    # 'PD': 'Publication Date',
    # 'PY': 'Year Published',
    # 'VL': 'Volume',
    # 'IS': 'Issue',
    # 'SI': 'Special Issue',
    # 'PN': 'Part Number',
    # 'SU': 'Supplement',
    # 'MA': 'Meeting Abstract',
    # 'BP': 'Beginning Page',
    # 'EP': 'Ending Page',
    # 'AR': 'Article Number',
    'DI': 'DOI',
    'D2': 'BDOI',
    # 'EA': 'Early access date',
    # 'EY': 'Early access year',
    # 'PG': 'Page Count',
    # 'P2': 'Chapter Count (Book Citation Index)',
    # 'WC': 'Web of Science Categories',
    # 'SC': 'Research Areas',
    # 'GA': 'Document Delivery Number',
    # 'PM': 'PubMed ID',
    # 'UT': 'Accession Number',
    # 'OA': 'Open Access Indicator',
    # 'HP': 'ESI Hot Paper. Note that this field is valued only for ESI subscribers.',
    # 'HC': 'ESI Highly Cited Paper. Note that this field is valued only for ESI subscribers.',
    # 'DA': 'Date this report was generated.',
    # 'ER': 'End of Record',
    # 'EF': 'End of File'
}

paper_pal_template = """PaperPal is a large language model trained by OpenAI.
PaperPal is designed to answer questions from a TEXT and provide accurate and in-depth responses.
As a language model, PaperPal is able to generate human-like text based on the input it receives, allowing it to engage in natural-sounding conversations and provide responses that are coherent and relevant to the topic at hand.
If you do not know an answer, say that you don't know and don't try to guess or make up an answer.
If you don't have enough information in the TEXT to answer a question, you can ask for more information.

TEXT: {text}

{history}
Human: {input}
PaperPal:"""